FROM golang:latest

ADD main.go /go/main.go

RUN sed 's/CLOUD_PROVIDER/Azure/' /go/main.go > /go/azure.go

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-s -w' /go/azure.go

ENTRYPOINT /go/azure

# https server listens on port 8080.
EXPOSE 8080