FROM golang:latest

ADD main.go /go/main.go

RUN sed 's/CLOUD_PROVIDER/GCloud/' /go/main.go > /go/gcloud.go

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-s -w' /go/gcloud.go

ENTRYPOINT /go/gcloud

# https server listens on port 8080.
EXPOSE 8080